### ISSUE TITLE
Custom DNS for pihole container

### ISSUE THREAD

**Issue by toffee** [HolgerHees/smartserver#21] opened 2024-09-15 10:03 UTC
Right now the pihole container is using Google DNS:
```
# podman exec -it pihole /bin/bash
root@590fcdbd7211:/# cat /etc/resolv.conf
nameserver 8.8.8.8
nameserver 8.8.4.4
```
As I mentioned previously (#18) in my setup Google DNS are not reachable, so I would like to modify the DNS used by pihole container.

I see two options:
 * to provide the [--dns](https://docs.docker.com/engine/network/#dns-services) options when the container is created and provide the IPs from dns_forward_ip_addresses
 * add a volume to the container which overrides the /etc/resolv.conf (now it forwards to 127.0.0.1, but cand be changed to iterate dns_forward_ip_addresses)

These changes are in a17fc84fd36099c2c07a5d6747a399e875a72540 (the second option commented).

What do you think - make sense to include one of this solutions into your code base?

**Comment by HolgerHees** [comment] 2024-09-15 12:11
I confirmed that this resolv.conf behavior is related to the macvlan network which is used by pihole and minidlna.

the normal flow of dns resolving should look like

CLIENT DNS: => `client => pihole => {{default_server_ip}} (dnsmasq) => dns_forward_ip_addresses`

CONTAINER DNS: => `container => resolve.conf 172.16.0.1 (podman dns) => 127.0.0.1 (dnsmasq) => dns_forward_ip_addresses`

the unexpected flow for macvlan containers (pihole & minidlna) are
               
MACVLAN CONTAINER DNS: => `macvlan container => resolve.conf 8.8.8.8 & 8.8.4.4`

I aggress to fix this by adding a container_dns option, but I would set this to {{default_server_ip}} to have this flow

CONTAINER DNS: => `container => resolve.conf {{default_server_ip}} (dnsmasq) => dns_forward_ip_addresses`

what do you think about? I committed this change already to master https://github.com/HolgerHees/smartserver/commit/fe7273c096efc8d132f1587cf2c2338a4462659c

btw. I also tried, setting this dns as part of the macvlan network creation, but currently it looks like the ansible podman_network module does not support this.

**Comment by toffee** [comment] 2024-09-15 13:30
Thanks! Looks good to me. 

The DNS resolving path to the upstream servers it's uniform between two types of networks (isolated and macvlan). The only drawback I see is that all containers (no mater the network type) depends on dnsmasq, but I think it's acceptable.

Being here (at the options you can pass to container for DNS) I'm wondering if it's an improvement to pass also the --hostname (with default to container_name) when create the container. I see the benefit that the hostname is displayed on shell prompt and for some containers it's displayed on UI (for pihole se image bellow):
![image](https://github.com/user-attachments/assets/f18a6cd5-3e67-43af-8e67-50eac14d4c65)

**Comment by HolgerHees** [comment] 2024-09-15 15:08
I agree that the dependency on dnsmasq is problematic. But the reason is to resolve *.<my_smartserver_domain> (like grafana.smartserver.com or openhab.smartserver.com) to your smartserver ip.

the differentiation for me is.

- dnsmasq is resolving everything
- pihole is for filtering and forwarding the rest

so, by choosing one of these dns, you can decide which kind of dns you want. Filtered or unfiltered.

and I like the ideas of providing the hostname! It is changed and committed https://github.com/HolgerHees/smartserver/commit/f28a1c442570728b674047eecac8cbd3b6124c6f

**Comment by toffee** [comment] 2024-09-17 16:46
I've integrated these changes and work fine! Thank you!

But, I found a situation (somehow annoying) related to DNS when pihole is the DNS for local devices. Probably you did not notice it because are using the dnsmasq for local devices DNS.

Seems that when during infrastructure updates (running ansible scripts) there are a significant amount of time while pihole container is created but not started. The dnsmasq container is started on [demand](https://github.com/HolgerHees/smartserver/blob/c31590b4e5442db3d151811dde7f3be7f359e5c6/roles/dnsmasq/tasks/main.yml#L97) but pihole container is started when handlers are [run](https://github.com/HolgerHees/smartserver/blob/c31590b4e5442db3d151811dde7f3be7f359e5c6/server.yml#L145)

You can see in bellow screenshot, pihole is not started:
![image](https://github.com/user-attachments/assets/60f8af01-5d21-47a2-90f5-34a6e52f2ba0)

My suggestion is to start pihole on demand too when dns_type is pihole in order to shorten the period while local DNS clients fail to resolve.

**Comment by HolgerHees** [comment] 2024-09-17 17:53
make sense to me. I don't check for dns_type == 'pihole', I do it always if necessary. https://github.com/HolgerHees/smartserver/commit/238eb1d6ca6f0f971f8a3c19fda1bdc7c6104de1

**Comment by toffee** [comment] 2024-09-19 11:55
Thank you!

**Closed** 2024-09-19 17:29 UTC
